# Generated by Django 3.2.6 on 2023-01-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='category', max_length=512),
        ),
    ]
