# Generated by Django 3.2.6 on 2023-01-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productlist'),
        ),
    ]
