# Generated by Django 3.2.6 on 2023-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seen_count',
            field=models.IntegerField(default=0),
        ),
    ]
