# Generated by Django 3.2.6 on 2023-01-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20230125_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count_in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='announcement_code',
            field=models.CharField(default='0x1234', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='customs_clearance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='live_location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Gori', 'Gori')], default='Tbilisi', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Gori', 'Gori'), ('Kutaisi', 'Kutaisi'), ('Batumi', 'Batumi'), ('Rustavi', 'Rustavi')], default='Tbilisi', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
