# Generated by Django 4.0 on 2023-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_transiter',
            field=models.BooleanField(default=False),
        ),
    ]
