# Generated by Django 4.0 on 2023-03-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_id_number_user_is_transiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_reviews',
        ),
    ]
