# Generated by Django 4.0 on 2023-03-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_product_num_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transiter_products', to='base.user'),
        ),
    ]
