# Generated by Django 3.2.6 on 2023-01-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
