# Generated by Django 3.2.6 on 2023-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='announcement_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='live_location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Gori', 'Gori')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Gori', 'Gori'), ('Kutaisi', 'Kutaisi'), ('Batumi', 'Batumi'), ('Rustavi', 'Rustavi')], max_length=200),
        ),
    ]
