# Generated by Django 4.0 on 2023-03-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_id_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
