# Generated by Django 4.0 on 2023-03-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='base.user'),
        ),
    ]
