# Generated by Django 4.0 on 2023-03-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_userfollowers_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
